lock_n_go:
  name: Lock 'n' go
  description: "Nuki Lock 'n' Go"
  target:
    entity:
      integration: nuki
      domain: lock
  fields:
    unlatch:
      name: unlatch
      description: Whether to unlatch the lock.
      example: false
      default: false
      selector:
        boolean:
