# Describes the format for available fan services
set_speed:
  description: Sets fan speed.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "fan.living_room"
    speed:
      description: Speed setting
      example: "low"

set_preset_mode:
  description: Set preset mode for a fan device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "fan.kitchen"
    preset_mode:
      description: New value of preset mode
      example: "auto"

set_percentage:
  description: Sets fan speed percentage.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "fan.living_room"
    percentage:
      description: Percentage speed setting
      example: 25

turn_on:
  description: Turns fan on.
  fields:
    entity_id:
      description: Names(s) of the entities to turn on
      example: "fan.living_room"
    speed:
      description: Speed setting
      example: "high"
    percentage:
      description: Percentage speed setting
      example: 75
    preset_mode:
      description: Preset mode setting
      example: "auto"

turn_off:
  description: Turns fan off.
  fields:
    entity_id:
      description: Names(s) of the entities to turn off
      example: "fan.living_room"

oscillate:
  description: Oscillates the fan.
  fields:
    entity_id:
      description: Name(s) of the entities to oscillate
      example: "fan.desk_fan"
    oscillating:
      description: Flag to turn on/off oscillation
      example: true

toggle:
  description: Toggle the fan on/off.
  fields:
    entity_id:
      description: Name(s) of the entities to toggle
      example: "fan.living_room"

set_direction:
  description: Set the fan rotation.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "fan.living_room"
    direction:
      description: The direction to rotate. Either 'forward' or 'reverse'
      example: "forward"
