select_next:
  description: Select the next options of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to select the next value for.
      example: input_select.my_select
    cycle:
      description: If the option should cycle from the last to the first (defaults to true).
      example: true
select_option:
  description: Select an option of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to select the value.
      example: input_select.my_select
    option:
      description: Option to be selected.
      example: '"Item A"'
select_previous:
  description: Select the previous options of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to select the previous value for.
      example: input_select.my_select
    cycle:
      description: If the option should cycle from the first to the last (defaults to true).
      example: true
select_first:
  description: Select the first option of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to select the first value for.
      example: input_select.my_select
select_last:
  description: Select the last option of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to select the last value for.
      example: input_select.my_select
set_options:
  description: Set the options of an input select entity.
  fields:
    entity_id:
      description: Entity id of the input select to set the new options for.
      example: input_select.my_select
    options:
      description: Options for the input select entity.
      example: '["Item A", "Item B", "Item C"]'
reload:
  description: Reload the input_select configuration.
